### ISSUE TITLE
Get slider value for HA light brightness

### ISSUE THREAD

**Issue by racally** [strange-v/ha_deck#16]
Hi,

I have tried every possible combination i can think of to get the slider value and pass to HA, can you help?
How do i pass the slider value into brightness attribute? 

```
        - type: slider
          position: 361, 127
          dimensions: 108x342
          text: Den Bright
          id: test
          min: 0
          max: 255
          enabled: return true;
          value:  return id(den_light_brt).state;
          on_change:
            homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.switchlinc_dimmer_44_ea_66
                brightness: ????
```
```
sensor:
  - platform: homeassistant
    id: den_light_brt
    entity_id: light.switchlinc_dimmer_44_ea_66
    attribute: brightness
    name: Den Light Brt
    internal: true
```

--

**Comment by strange-v** [comment]
```yaml
      - type: slider
        position: 90, 8
        text: Left
        min: 0
        max: 255
        value: |-
          return (id(living_room_led_a).state == "on") ? id(living_room_led_a_brightness).state : 0;
        on_change:
          homeassistant.service:
            service: light.turn_on
            data:
              entity_id: light.living_room_light_controller_led_a
              brightness: !lambda return x;
```
