### ISSUE TITLE
Read home assistant sensor

### ISSUE THREAD

**Issue by maikrolf** [strange-v/ha_deck#2]
Is it possible to read/show home assistant sensor of binary data in the display, if yes how can i do this?

Thanks you very much Maik
P.S. great project i love it

**Comment by strange-v** [comment]
Yes, it's possible. You need to add the sensor itself:
```yaml
sensor:
- platform: homeassistant
  id: outside_temerature
  entity_id: sensor.rfm_node_3_temperature_2
```

and then use it in a widget:
```yaml
- type: value-card
  position: 244, 216
  text: "Outside"
  icon: 󰔏
  unit: °C
  value: |-
    char buff[10] = "-";
    if (isnan(id(outside_temerature).state))
      return std::string(buff);
    sprintf(buff, "%.1f", id(outside_temerature).state);
    return std::string(buff);
```
