### ISSUE TITLE
Feature request - highlight button when pressing

### ISSUE THREAD

**Issue by andypnz** [strange-v/ha_deck#23]
Hi. Amazing - thank you for sharing this! Works super well :slight_smile:

One question:
Is it possible for a widget ‘button’ to have an ‘on_click’ action to highlight the button to show it is being pressed? Basically, an ‘on click toggle: true’ type function.

```
        - type: button
          position: 362, 8
          text: Set 23
          icon: 󰐸
          enabled: return true;
          on_click:
            #### something to show the button is being pressed ####
            then:
              - homeassistant.service:
                  service: script.set_heat_pump_23
```

Thank you again! A super nice mini display / control center for HA
