### ISSUE TITLE
Error: Please specify flash_size within esp32 configuration only.

### ISSUE THREAD

**Issue by brixharlem** [strange-v/ha_deck#8]
I very much like your project and I'm trying to get your example yaml running, but I'm getting an error message. It seems to be a problem with the 
platformio_options:
    board_upload.flash_size: 16MB
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "../../../custom_partitions_3584.csv"

That's the error message, which prevents flashing the device:

INFO ESPHome 2023.12.8
INFO Reading configuration /config/esphome/esp32-s3-display-lvgl-wide.yaml...
Failed config

esp32: None
  
  Please specify flash_size within esp32 configuration only.
  board: esp32-s3-devkitc-1
  framework: 
    version: 2.0.5
    source: ~3.20005.0
    platform_version: platformio/espressif32@5.4.0
    type: arduino
  flash_size: 4MB
  variant: ESP32S3

Any idea? Thank you very much!

**Comment by brixharlem** [comment]
It's working now. I removed the board_upload.flash_size: 16MB from "platformio_options:" and added "flash_size: 16MB" to esp32

```
esphome:
  name: esp32-display-lvgl
  friendly_name: esp32-display-lvgl
  platformio_options:
#    board_upload.flash_size: 16MB
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "/config/esphome/lvgl/custom_partitions_3584.csv"

esp32:
  board: esp32-s3-devkitc-1
  framework: 
    type: arduino
  flash_size: 16MB
```
